name: mistdumper
description: A configurable pattern finder for static analysis written in Dart
version: 1.0.2
homepage: https://github.com/Midi12/mistdumper
repository: https://github.com/Midi12/mistdumper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pefile: ^1.0.0-dev.1
  args: ^2.1.0
  json_annotation: ^4.0.1
  ansicolor: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^2.0.1
  json_serializable: ^4.1.1
